# Generated by Django 4.2.4 on 2023-10-31 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.path


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("miscellaneous", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectImageField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("json_field", models.JSONField(blank=True, default=dict, null=True)),
                ("slug", models.CharField(max_length=255)),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                ("year", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "image",
                    models.ImageField(upload_to=utils.path.get_project_pics_path),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="gallery",
            name="caption",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("json_field", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "vertical",
                    models.PositiveIntegerField(
                        choices=[(2, "Ml"), (1, "AR/VR AND DEV "), (3, "Robotics")],
                        default=1,
                    ),
                ),
                ("name", models.CharField()),
                ("description", models.TextField()),
                ("redirect_link", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="miscellaneous.projectimagefield",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Achivements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("json_field", models.JSONField(blank=True, default=dict, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("year", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "image",
                    models.ImageField(upload_to=utils.path.get_achivments_pics_path),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
