# Generated by Django 4.2.4 on 2023-08-27 06:23

from django.db import migrations, models
import utils.path


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alum",
            name="profile_pic",
            field=models.ImageField(
                blank=True, upload_to=utils.path.get_profile_pics_path
            ),
        ),
        migrations.AlterField(
            model_name="team_member",
            name="profile_pic",
            field=models.ImageField(
                blank=True, upload_to=utils.path.get_profile_pics_path
            ),
        ),
    ]
